import React from 'react'

const InstaMart = () => {
  return (
    <>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
    <div>InstaMart</div>
  </> 
  )
}

export default InstaMart